/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos.layerd.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pos.layerd.controller.CustomerController;
import pos.layerd.controller.ItemController;
import pos.layerd.controller.OrderController;
import pos.layerd.dto.CustomerDto;
import pos.layerd.dto.ItemDto;
import pos.layerd.dto.OrderDetailsDto;
import pos.layerd.dto.OrderDto;


/**
 *
 * @author Hiran
 */
public class OrderPanel extends javax.swing.JPanel {

    CustomerController customerController;
    ItemController itemController;
    ArrayList<OrderDetailsDto> orderDetailsDtos = new ArrayList<>();
    OrderController orderController;
    /**
     * Creates new form OrderPanel
     */
    public OrderPanel() {
        customerController = new CustomerController();
        itemController = new ItemController();
        orderController = new OrderController();
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        headerlabel = new javax.swing.JLabel();
        fromPanel = new javax.swing.JPanel();
        ordeIdLabel = new javax.swing.JLabel();
        orderIdText = new javax.swing.JTextField();
        customerIdLabel1 = new javax.swing.JLabel();
        orderCustIdText = new javax.swing.JTextField();
        searchCustomer = new javax.swing.JButton();
        custDataLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        itemIdLabel = new javax.swing.JLabel();
        itemIdText = new javax.swing.JTextField();
        addItem = new javax.swing.JButton();
        itemDataLabel2 = new javax.swing.JLabel();
        qtyLabel = new javax.swing.JLabel();
        qtyText = new javax.swing.JTextField();
        discountLabel = new javax.swing.JLabel();
        discountText = new javax.swing.JTextField();
        searchItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemDeatailsTable = new javax.swing.JTable();
        placeOrderButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        basePanel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        headerlabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerlabel.setForeground(new java.awt.Color(51, 51, 255));
        headerlabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        headerlabel.setText("Order");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        fromPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ordeIdLabel.setText("Order Id");
        fromPanel.add(ordeIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, -1, 22));

        orderIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderIdTextActionPerformed(evt);
            }
        });
        fromPanel.add(orderIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 15, 108, -1));

        customerIdLabel1.setText("Customer Id");
        fromPanel.add(customerIdLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 43, -1, 22));
        fromPanel.add(orderCustIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 46, 108, -1));

        searchCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchCustomer.setText("Search");
        searchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerActionPerformed(evt);
            }
        });
        fromPanel.add(searchCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 43, -1, -1));

        custDataLabel1.setBackground(new java.awt.Color(255, 255, 255));
        fromPanel.add(custDataLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 43, 392, 27));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 255));
        fromPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 88, 730, 10));

        itemIdLabel.setText("Item Id");
        fromPanel.add(itemIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 107, -1, 22));
        fromPanel.add(itemIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 107, 108, -1));

        addItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addItem.setText("Add Item");
        addItem.setActionCommand("");
        addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemActionPerformed(evt);
            }
        });
        fromPanel.add(addItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 177, -1, 22));

        itemDataLabel2.setBackground(new java.awt.Color(255, 255, 255));
        fromPanel.add(itemDataLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 104, 422, 27));

        qtyLabel.setText("Qty");
        fromPanel.add(qtyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 149, -1, 22));
        fromPanel.add(qtyText, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 149, 108, -1));

        discountLabel.setText("Discount");
        fromPanel.add(discountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 177, -1, 22));
        fromPanel.add(discountText, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 177, 154, -1));

        searchItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchItem.setText("Search");
        searchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchItemActionPerformed(evt);
            }
        });
        fromPanel.add(searchItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 104, -1, -1));

        itemDeatailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(itemDeatailsTable);

        fromPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 205, 695, 161));

        placeOrderButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        placeOrderButton.setText("Place Order");
        placeOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderButtonActionPerformed(evt);
            }
        });
        fromPanel.add(placeOrderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 384, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hiran\\Desktop\\ijse\\online-shopping-e-commerce-concept-wooden-block-icon-cart-standing-computer-keyboard-viewed-44905065.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        fromPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 530));

        javax.swing.GroupLayout basePanelLayout = new javax.swing.GroupLayout(basePanel);
        basePanel.setLayout(basePanelLayout);
        basePanelLayout.setHorizontalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addComponent(fromPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        basePanelLayout.setVerticalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fromPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void orderIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderIdTextActionPerformed

    private void searchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerActionPerformed
        // TODO add your handling code here:
        searchCustomer();
    }//GEN-LAST:event_searchCustomerActionPerformed

    private void addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemActionPerformed
        // TODO add your handling code here:
        addTable();
    }//GEN-LAST:event_addItemActionPerformed

    private void searchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemActionPerformed
        try {
            searchItems();
        } catch (Exception ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchItemActionPerformed

    private void placeOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderButtonActionPerformed
        // TODO add your handling code here:
        placeOrder();
    }//GEN-LAST:event_placeOrderButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItem;
    private javax.swing.JPanel basePanel;
    private javax.swing.JLabel custDataLabel1;
    private javax.swing.JLabel customerIdLabel1;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JTextField discountText;
    private javax.swing.JPanel fromPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel headerlabel;
    private javax.swing.JLabel itemDataLabel2;
    private javax.swing.JTable itemDeatailsTable;
    private javax.swing.JLabel itemIdLabel;
    private javax.swing.JTextField itemIdText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel ordeIdLabel;
    private javax.swing.JTextField orderCustIdText;
    private javax.swing.JTextField orderIdText;
    private javax.swing.JButton placeOrderButton;
    private javax.swing.JLabel qtyLabel;
    private javax.swing.JTextField qtyText;
    private javax.swing.JButton searchCustomer;
    private javax.swing.JButton searchItem;
    // End of variables declaration//GEN-END:variables

    private void loadTable() {
        String[] columns = {"Item Code", "Qty", "Discount"};
        DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };

        itemDeatailsTable.setModel(dtm);

    }

    private void searchCustomer() {

        try {
            String custId = orderCustIdText.getText();

            CustomerDto customerDtol = customerController.searchCustomer(custId);
            if (customerDtol != null) {
                custDataLabel1.setText(customerDtol.getNames() + "," + customerDtol.getAddress());

            } else {
                JOptionPane.showMessageDialog(this, "Customer Not Found");

            }
        } catch (Exception ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex);
        }

    }

    private void searchItems() throws Exception {

        try {
            String itemId = itemIdText.getText();

            ItemDto itemDtol = itemController.getItem(itemId);
            if (itemDtol != null) {
                itemDataLabel2.setText(itemDtol.getDescription() + "," + itemDtol.getUnitPrice() + "," + itemDtol.getQty());

            } else {
                JOptionPane.showMessageDialog(this, "Item Not Found");
            }

        } catch (Exception ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex);

        }

    }

    private void addTable() {
   
        OrderDetailsDto orderDetailsDto = new OrderDetailsDto("", itemIdText.getText(), Integer.parseInt(qtyText.getText()), Double.parseDouble(discountText.getText()));
        orderDetailsDtos.add(orderDetailsDto);
        
        
        Object[] rowData = {orderDetailsDto.getItemCode(),orderDetailsDto.getQty(),orderDetailsDto.getDiscount()};
        
        DefaultTableModel dtm = (DefaultTableModel) itemDeatailsTable.getModel();
        dtm.addRow(rowData);
         cleanItemData();
    }
       private void cleanItemData() {
        itemIdText.setText("");
        qtyText.setText("");
        discountText.setText("");
        itemDataLabel2.setText("");
    }

    private void placeOrder() {
        try {
                 OrderDto orderDto = new OrderDto(orderIdText.getText(), orderCustIdText.getText(), orderDetailsDtos);
        String result = orderController.placeOrder(orderDto);
        JOptionPane.showMessageDialog(this, result);
                    
        } catch (Exception ex) {
    
        Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
         JOptionPane.showMessageDialog(this, ex);
        }
   
    }

}
